"""GTFS-RT city configuration mappings."""

# GTFS-RT city configs: static GTFS zip + realtime TripUpdates URL
GTFSRT_CITIES = {
    "gtfsrt_poznan": {
        "gtfs_url": "https://www.ztm.poznan.pl/pl/dla-deweloperow/getGTFSFile",
        "rt_url": "https://www.ztm.poznan.pl/pl/dla-deweloperow/getGtfsRtFile?file=trip_updates.pb",
        "vehicles_url": "https://www.ztm.poznan.pl/pl/dla-deweloperow/getGtfsRtFile?file=vehicle_dictionary.csv",
        "positions_url": "https://www.ztm.poznan.pl/pl/dla-deweloperow/getGtfsRtFile?file=vehicle_positions.pb",
        "label": "ZTM Pozna\u0144",
    },
    "gtfsrt_lublin": {
        "gtfs_url": "https://cdn.zbiorkom.live/gtfs/lublin.zip",
        "rt_url": "https://cdn.zbiorkom.live/gtfs-rt/lublin.pb",
        "positions_url": "https://cdn.zbiorkom.live/gtfs-rt/lublin.pb",
        "label": "ZTM Lublin",
    },
    "gtfsrt_kielce": {
        "gtfs_url": "https://cdn.zbiorkom.live/gtfs/kielce.zip",
        "rt_url": "https://cdn.zbiorkom.live/gtfs-rt/kielce.pb",
        "positions_url": "https://cdn.zbiorkom.live/gtfs-rt/kielce.pb",
        "label": "MPK Kielce",
    },
    "gtfsrt_radom": {
        "gtfs_url": "https://cdn.zbiorkom.live/gtfs/radom.zip",
        "rt_url": "https://cdn.zbiorkom.live/gtfs-rt/radom.pb",
        "positions_url": "https://cdn.zbiorkom.live/gtfs-rt/radom.pb",
        "label": "MZDiK Radom",
    },
    "gtfsrt_czestochowa": {
        "gtfs_url": "https://api.zbiorkom.live/api6-open/czestochowa/gtfs/default",
        "rt_url": "https://api.zbiorkom.live/api6-open/czestochowa/gtfsRealtime/default/tripUpdates",
        "positions_url": "https://api.zbiorkom.live/api6-open/czestochowa/gtfsRealtime/default/vehiclePositions",
        "positions_format": "gtfsrt_protobuf",
        "label": "MPK Cz\u0119stochowa",
    },
    "gtfsrt_elblag": {
        "gtfs_url": "https://cdn.zbiorkom.live/gtfs/elblag.zip",
        "rt_url": "https://cdn.zbiorkom.live/gtfs-rt/elblag.pb",
        "positions_url": "https://cdn.zbiorkom.live/gtfs-rt/elblag.pb",
        "label": "ZKM Elbl\u0105g",
    },
    "gtfsrt_gorzow": {
        "gtfs_url": "https://cdn.zbiorkom.live/gtfs/gorzow.zip",
        "rt_url": "https://cdn.zbiorkom.live/gtfs-rt/gorzow.pb",
        "positions_url": "https://cdn.zbiorkom.live/gtfs-rt/gorzow.pb",
        "label": "MZK Gorz\u00f3w Wlkp.",
    },
    "gtfsrt_suwalki": {
        "gtfs_url": "https://cdn.zbiorkom.live/gtfs/suwalki.zip",
        "rt_url": "https://cdn.zbiorkom.live/gtfs-rt/suwalki.pb",
        "positions_url": "https://cdn.zbiorkom.live/gtfs-rt/suwalki.pb",
        "label": "PGK Suwa\u0142ki",
    },
    "gtfsrt_przemysl": {
        "gtfs_url": "https://cdn.zbiorkom.live/gtfs/przemysl.zip",
        "rt_url": "https://cdn.zbiorkom.live/gtfs-rt/przemysl.pb",
        "positions_url": "https://cdn.zbiorkom.live/gtfs-rt/przemysl.pb",
        "label": "MZK Przemy\u015bl",
    },
    "gtfsrt_rybnik": {
        "gtfs_url": "https://cdn.zbiorkom.live/gtfs/rybnik.zip",
        "rt_url": "https://cdn.zbiorkom.live/gtfs-rt/rybnik.pb",
        "positions_url": "https://cdn.zbiorkom.live/gtfs-rt/rybnik.pb",
        "label": "ZTZ Rybnik",
    },
    "gtfsrt_kutno": {
        "gtfs_url": "https://cdn.zbiorkom.live/gtfs/kutno.zip",
        "rt_url": "https://cdn.zbiorkom.live/gtfs-rt/kutno.pb",
        "positions_url": "https://cdn.zbiorkom.live/gtfs-rt/kutno.pb",
        "label": "MZK Kutno",
    },
    "gtfsrt_legnica": {
        "gtfs_url": "https://cdn.zbiorkom.live/gtfs/legnica.zip",
        "rt_url": "https://cdn.zbiorkom.live/gtfs-rt/legnica.pb",
        "positions_url": "https://cdn.zbiorkom.live/gtfs-rt/legnica.pb",
        "label": "MPK Legnica",
    },
    "gtfsrt_szczecin": {
        "gtfs_url": "https://www.zditm.szczecin.pl/storage/gtfs/gtfs.zip",
        "rt_url": "https://www.zditm.szczecin.pl/storage/gtfs/gtfs-rt-trips.pb",
        "positions_url": "https://www.zditm.szczecin.pl/api/v2/vehicles?format=json",
        "label": "ZDiTM Szczecin",
    },
    "gtfsrt_warszawa": {
        "gtfs_url": "https://mkuran.pl/gtfs/warsaw.zip",
        "rt_url": "https://mkuran.pl/gtfs/warsaw/vehicles.pb",
        "positions_url": "https://mkuran.pl/gtfs/warsaw/positions.json",
        "label": "ZTM Warszawa",
    },
    "gtfsrt_elk": {
        "gtfs_url": "https://mkuran.pl/gtfs/elk.zip",
        "rt_url": "https://mkuran.pl/gtfs/elk.pb",
        "positions_url": "https://mkuran.pl/gtfs/elk.pb",
        "label": "MZK Ełk",
    },
    "gtfsrt_wkd": {
        "gtfs_url": "https://mkuran.pl/gtfs/wkd.zip",
        "rt_url": "https://mkuran.pl/gtfs/wkd.pb",
        "label": "WKD",
    },
    "gtfs_bialystok": {
        "gtfs_url": "https://api.zbiorkom.live/api6-open/bialystok/gtfs/default",
        "rt_url": "https://api.zbiorkom.live/api6-open/bialystok/gtfsRealtime/default/tripUpdates",
        "positions_url": "https://api.zbiorkom.live/api6-open/bialystok/gtfsRealtime/default/vehiclePositions",
        "positions_format": "gtfsrt_protobuf",
        "label": "BKM Białystok",
    },
    "gtfs_olsztyn": {
        "gtfs_url": "https://api.zbiorkom.live/api6-open/olsztyn/gtfs/default",
        "rt_url": "https://api.zbiorkom.live/api6-open/olsztyn/gtfsRealtime/default/tripUpdates",
        "positions_url": "https://api.zbiorkom.live/api6-open/olsztyn/gtfsRealtime/default/vehiclePositions",
        "positions_format": "gtfsrt_protobuf",
        "label": "ZDZiT Olsztyn",
    },
    "gtfs_opole": {
        "gtfs_url": "https://api.zbiorkom.live/api6-open/opole/gtfs/default",
        "rt_url": "https://api.zbiorkom.live/api6-open/opole/gtfsRealtime/default/tripUpdates",
        "positions_url": "https://api.zbiorkom.live/api6-open/opole/gtfsRealtime/default/vehiclePositions",
        "positions_format": "gtfsrt_protobuf",
        "label": "MZK Opole",
    },
    "gtfsrt_wroclaw": {
        "gtfs_url": "https://cdn.zbiorkom.live/gtfs/wroclaw.zip",
        "rt_url": "https://mapadlugoleka.klosok.eu/vehicle_positions.pb",
        "positions_url": "https://mapadlugoleka.klosok.eu/vehicle_positions.pb",
        "label": "MPK Wroc\u0142aw",
    },
    "gtfs_rzeszow": {
        "gtfs_url": "https://api.zbiorkom.live/api6-open/rzeszow/gtfs/default",
        "rt_url": "https://api.zbiorkom.live/api6-open/rzeszow/gtfsRealtime/default/tripUpdates",
        "positions_url": "https://api.zbiorkom.live/api6-open/rzeszow/gtfsRealtime/default/vehiclePositions",
        "positions_format": "gtfsrt_protobuf",
        "label": "ZTM Rzeszów",
    },
    "gtfs_kalisz": {
        "gtfs_url": "https://api.zbiorkom.live/api6-open/kalisz/gtfs/default",
        "rt_url": "https://api.zbiorkom.live/api6-open/kalisz/gtfsRealtime/default/tripUpdates",
        "positions_url": "https://api.zbiorkom.live/api6-open/kalisz/gtfsRealtime/default/vehiclePositions",
        "positions_format": "gtfsrt_protobuf",
        "label": "MZK Kalisz",
    },
    "gtfs_konin": {
        "gtfs_url": "https://api.zbiorkom.live/api6-open/konin/gtfs/default",
        "rt_url": "https://api.zbiorkom.live/api6-open/konin/gtfsRealtime/default/tripUpdates",
        "positions_url": "https://api.zbiorkom.live/api6-open/konin/gtfsRealtime/default/vehiclePositions",
        "positions_format": "gtfsrt_protobuf",
        "label": "MZK Konin",
    },
    "gtfs_koszalin": {
        "gtfs_url": "https://api.zbiorkom.live/api6-open/koszalin/gtfs/default",
        "rt_url": "https://api.zbiorkom.live/api6-open/koszalin/gtfsRealtime/default/tripUpdates",
        "positions_url": "https://api.zbiorkom.live/api6-open/koszalin/gtfsRealtime/default/vehiclePositions",
        "positions_format": "gtfsrt_protobuf",
        "label": "MZK Koszalin",
    },
    "gtfs_krosno": {
        "gtfs_url": "https://api.zbiorkom.live/api6-open/krosno/gtfs/default",
        "rt_url": "https://api.zbiorkom.live/api6-open/krosno/gtfsRealtime/default/tripUpdates",
        "positions_url": "https://api.zbiorkom.live/api6-open/krosno/gtfsRealtime/default/vehiclePositions",
        "positions_format": "gtfsrt_protobuf",
        "label": "MKS Krosno",
    },
    "gtfs_pila": {
        "gtfs_url": "https://api.zbiorkom.live/api6-open/pila/gtfs/default",
        "rt_url": "https://api.zbiorkom.live/api6-open/pila/gtfsRealtime/default/tripUpdates",
        "positions_url": "https://api.zbiorkom.live/api6-open/pila/gtfsRealtime/default/vehiclePositions",
        "positions_format": "gtfsrt_protobuf",
        "label": "MZK Piła",
    },
    "gtfs_plock": {
        "gtfs_url": "https://api.zbiorkom.live/api6-open/plock/gtfs/default",
        "rt_url": "https://api.zbiorkom.live/api6-open/plock/gtfsRealtime/default/tripUpdates",
        "positions_url": "https://api.zbiorkom.live/api6-open/plock/gtfsRealtime/default/vehiclePositions",
        "positions_format": "gtfsrt_protobuf",
        "label": "KM Płock",
    },
    "gtfs_siedlce": {
        "gtfs_url": "https://api.zbiorkom.live/api6-open/siedlce/gtfs/default",
        "rt_url": "https://api.zbiorkom.live/api6-open/siedlce/gtfsRealtime/default/tripUpdates",
        "positions_url": "https://api.zbiorkom.live/api6-open/siedlce/gtfsRealtime/default/vehiclePositions",
        "positions_format": "gtfsrt_protobuf",
        "label": "MPK Siedlce",
    },
    "gtfs_starachowice": {
        "gtfs_url": "https://api.zbiorkom.live/api6-open/starachowice/gtfs/default",
        "rt_url": "https://api.zbiorkom.live/api6-open/starachowice/gtfsRealtime/default/tripUpdates",
        "positions_url": "https://api.zbiorkom.live/api6-open/starachowice/gtfsRealtime/default/vehiclePositions",
        "positions_format": "gtfsrt_protobuf",
        "label": "MZK Starachowice",
    },
    "gtfs_tarnow": {
        "gtfs_url": "https://api.zbiorkom.live/api6-open/tarnow/gtfs/default",
        "rt_url": "https://api.zbiorkom.live/api6-open/tarnow/gtfsRealtime/default/tripUpdates",
        "positions_url": "https://api.zbiorkom.live/api6-open/tarnow/gtfsRealtime/default/vehiclePositions",
        "positions_format": "gtfsrt_protobuf",
        "label": "MPK Tarnów",
    },
    "gtfs_walbrzych": {
        "gtfs_url": "https://api.zbiorkom.live/api6-open/walbrzych/gtfs/default",
        "rt_url": "https://api.zbiorkom.live/api6-open/walbrzych/gtfsRealtime/default/tripUpdates",
        "positions_url": "https://api.zbiorkom.live/api6-open/walbrzych/gtfsRealtime/default/vehiclePositions",
        "positions_format": "gtfsrt_protobuf",
        "label": "ZKM Wałbrzych",
    },
    "gtfs_swinoujscie": {
        "gtfs_url": "https://api.zbiorkom.live/api6-open/swinoujscie/gtfs/default",
        "rt_url": "https://api.zbiorkom.live/api6-open/swinoujscie/gtfsRealtime/default/tripUpdates",
        "positions_url": "https://api.zbiorkom.live/api6-open/swinoujscie/gtfsRealtime/default/vehiclePositions",
        "positions_format": "gtfsrt_protobuf",
        "label": "KA Świnoujście",
    },
    "gtfs_bydgoszcz": {
        "gtfs_url": "https://mkuran.pl/gtfs/bydgoszcz.zip",
        "rt_url": None,
        "label": "ZDMiKP Bydgoszcz",
    },
    "gtfs_mielec": {
        "gtfs_url": "https://api.zbiorkom.live/api6-open/mielec/gtfs/default",
        "rt_url": "https://api.zbiorkom.live/api6-open/mielec/gtfsRealtime/default/tripUpdates",
        "positions_url": "https://api.zbiorkom.live/api6-open/mielec/gtfsRealtime/default/vehiclePositions",
        "positions_format": "gtfsrt_protobuf",
        "label": "MKS Mielec",
    },
    "gtfs_oswiecim": {
        "gtfs_url": "https://api.zbiorkom.live/api6-open/oswiecim/gtfs/default",
        "rt_url": "https://api.zbiorkom.live/api6-open/oswiecim/gtfsRealtime/default/tripUpdates",
        "positions_url": "https://api.zbiorkom.live/api6-open/oswiecim/gtfsRealtime/default/vehiclePositions",
        "positions_format": "gtfsrt_protobuf",
        "label": "MZK Oświęcim",
    },
    "gtfs_radomsko": {
        "gtfs_url": "https://api.zbiorkom.live/api6-open/radomsko/gtfs/default",
        "rt_url": "https://api.zbiorkom.live/api6-open/radomsko/gtfsRealtime/default/tripUpdates",
        "positions_url": "https://api.zbiorkom.live/api6-open/radomsko/gtfsRealtime/default/vehiclePositions",
        "positions_format": "gtfsrt_protobuf",
        "label": "MPK Radomsko",
    },
    "gtfs_debica": {
        "gtfs_url": "https://api.zbiorkom.live/api6-open/debica/gtfs/default",
        "rt_url": None,
        "label": "MKS Dębica",
    },
    "gtfs_kolobrzeg": {
        "gtfs_url": "https://api.zbiorkom.live/api6-open/kolobrzeg/gtfs/default",
        "rt_url": None,
        "label": "KM Kołobrzeg",
    },
    "gtfs_sanok": {
        "gtfs_url": "https://api.zbiorkom.live/api6-open/sanok/gtfs/default",
        "rt_url": None,
        "label": "SPGK Sanok",
    },
    "gtfs_ostroleka": {
        "gtfs_url": "https://api.zbiorkom.live/api6-open/ostroleka/gtfs/default",
        "rt_url": None,
        "label": "MZK Ostrołęka",
    },
    "gtfs_leszno": {
        "gtfs_url": "https://cdn.zbiorkom.live/gtfs/leszno.zip",
        "rt_url": None,
        "label": "MZK Leszno",
    },
    "gtfsrt_torun": {
        "gtfs_url": "https://api.zbiorkom.live/api6-open/torun/gtfs/default",
        "rt_url": "https://api.zbiorkom.live/api6-open/torun/gtfsRealtime/default/tripUpdates",
        "positions_url": "https://api.zbiorkom.live/api6-open/torun/gtfsRealtime/default/vehiclePositions",
        "positions_format": "gtfsrt_protobuf",
        "label": "MZK Toruń",
    },
    "gtfsrt_gzm": {
        "gtfs_url": None,  # Dynamic - fetched from CKAN API
        "gtfs_package_id": "317435cc-0075-4d10-b8ef-6e9b0010e90a",
        "rt_url": "https://gtfsrt.transportgzm.pl:5443/gtfsrt/gzm/tripUpdates",
        "positions_url": "https://gtfsrt.transportgzm.pl:5443/gtfsrt/gzm/vehiclePositions",
        "positions_format": "gtfsrt_protobuf",
        "label": "ZTM GZM (Katowice)",
    },
    "mpk_lodz": {
        "gtfs_url": "https://otwarte.miasto.lodz.pl/wp-content/uploads/2025/06/GTFS.zip",
        "rt_url": "https://otwarte.miasto.lodz.pl/wp-content/uploads/2025/06/trip_updates.bin",
        "positions_url": "https://otwarte.miasto.lodz.pl/wp-content/uploads/2025/06/vehicle_positions.bin",
        "label": "MPK \u0141\u00f3d\u017a",
    },
}
